name: ifac-wc-2020
channels:
  - pytorch
  - gpytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - matplotlib
  - ipython
  - pytorch
  - torchvision
  - gpytorch
  - pydash
  - pip
  - pip:
    - gym
